### ISSUE TITLE
RustConf 2023 link returns 404

### ISSUE THREAD

**Issue by welpo** [AccessKit/accesskit-website#11]
Hello!

The link in the ["AccessKit featured at RustConf" article](https://accesskit.dev/accesskit-featured-at-rustconf/) returns 404: https://rustconf.com/schedule/making-guis-accessible-across-platforms-and-languages-with-rust

Maybe it could be updated with the link to the talk on YouTube (I think this is it): https://www.youtube.com/watch?v=LRBKb6McgqA

**Comment by DataTriny** [comment]
Thanks @welpo, good catch!
