### ISSUE TITLE
Headings in the website blog

### ISSUE THREAD

**Issue by RastislavKish** [AccessKit/accesskit-website#14]
This is mostly a minor thing, but the [AccessKit Blog](https://accesskit.dev/blog/) is currently lacking heading tags for article links.

Screenreader users can indeed use the K key to navigate by links, but there are two issues with this approach:

1. One has to switch navigation keys after jumping to the main heading, which can be inconvenient and, in the first place, unexpected
2. In the future, if other links appear under the article title, for example, the author's name becomes a link pointing to their profile or there will be a preview section with a read more link, the keyboard navigation can become increasingly inconvenient (GitHub issues are actually a good example of this effect)

It would be great if the article links were tagged as headings, like done by blogs, news websites or search engines.

**Comment by DataTriny** [comment]
I don't think we will add more links in there anytime soon, so you can just tab through them.

With that being said, I tend to agree. I tried just replacing the `div`s by `h2`s but then the title gets too far apart from the text below and I'm not sure how to properly fix the CSS.

**Comment by RastislavKish** [comment]
Thanks for looking into this! Well, I'm not a web designer, but since you usually probably do want to have the [default top and bottom margins](https://www.w3schools.com/tags/tag_hn.asp) it would appear to me this is a fairly local change and as such can be just overwritten in the blog template?

**Comment by RastislavKish** [comment]
@DataTriny you mean the styling? I can not confirm the visual change as I'm blind, but I can open a PR and fire up a debug instance with the necessary changes if you're busy with other work. It's like 5 lines of code, shouldn't be a big deal.
